### ISSUE TITLE
todo list for version 4.0

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/crowsetta#146]
making an issue that's the to-do list for version 4.0 that tracks what issues to close, and puts them roughly in some order

- [x] rewrite API #120
- [x] add formats bass class #105 
- [x] write annotations as attrs classes #99 
  - [x] refactor existing formats in process 
    - [x] refactor generic-seq format, use `pandas` #63 
    - [x] #154 
    - [x] #134 
- [x] add formats sub-package #109 
- [x] change how annotation formats are listed #92 
  - would be good to have a convenient way to list the string names. `crowsetta.formats.names`?
- [x] refactor Transcriber class #144
- [x] remove entry points #94 
- [x] clean up `Annotation` class(es)
  - [x] rename `Annotation.audio_path` attribute to `notated_path` #148 
  - [x] why is seq attribute on Annotation optional? #149
  - [x] separate Annotation classes for SeqLike and BboxLike? #150
- [x] #156 
- [x] decide if we want to use `register_format` decorator #119 
- [x] remove `Stack` class for now #170
- [x] remove `'csv'` format (alias) #171
- [x] add example annotation files to package #90 
- [x] rewrite docs #152
   - [x] #157 
   - [x] #158 
- [x] add logo #17 
- [x] #21

**Comment by NickleDave** [comment]
Closed by [737a50c](https://github.com/vocalpy/crowsetta/commit/737a50c7aa4f125e8f241c1e7e792e998e713fdb)
