### ISSUE TITLE
to-do list for 4.1.0

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/crowsetta#200]
These were on #146 but none of them are critical to the new version actually working.
So I will release and move them to the to-dos for a next minor version

- [ ] add contributing.md #30 
- [ ] add vignettes #91
- [ ] (finish) adding typing #104
- [ ] make dvc a dev dependency and make "data for tests" into a dvc dataset #147
- [ ] add `nox` session to download test data #71

**Comment by NickleDave** [comment]
These are either done or backlog and we're past version 4.1, so I'm closing this
